# TikTok Uploader Default Configuation File

headless = true
quit_on_end = false

# Messing around with inputs
valid_path_names = ["path", "filename", "video", "video_path"]
valid_descriptions = ["description", "desc", "caption"]

# Selenium Webdriver Waits
implicit_wait = 5  # seconds
explicit_wait = 60 # seconds
extra_explicit_wait = 300 # seconds

supported_file_types = ["mp4", "mov", "avi", "wmv", "flv", "webm", "mkv", "m4v", "3gp", "3g2", "gif"]

max_description_length = 150 # characters

[paths]
	main = "https://www.tiktok.com/en"
	login = "https://www.tiktok.com/login/phone-or-email/email"
	upload = "https://www.tiktok.com/creator-center/upload?lang=en"

[disguising]
	user_agent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'

[selectors] # Selenium XPATH selectors

	[selectors.login]
		username_field = "//input[@name=\"username\"]"
		password_field = "//input[@type=\"password\"]"
		login_button = "//button[@type=\"submit\"]"
		
		alert_user_if_failed = true # sends an alert and waits instead of failing
	
		cookie_of_interest = "sessionid" # cookie to check if login was successful
		inbox_icon = "div[data-e2e='inbox-icon'][role='button']"

		profile = "a[data-e2e='nav-profile']"
		followers = "span[data-e2e='followers']"
		followers_box = 'div[role="dialog"][data-e2e="follow-info-popup"]'
		follow_back = "button[data-e2e='follow-button'][type='button']"
		videos_count = 'strong[data-e2e="video-views"]'
		three_dots = 'div[data-e2e="video-setting"]'
		delete_video = 'li[data-e2e="video-delete"] > button'
		confirm_delete_video = 'button[data-e2e="video-modal-delete"]'


	[selectors.upload]

		iframe = '//iframe[1]'
		
		split_window = "//button[./div[text()='Not now']]"
		upload_video = '//*[@id="root"]/div/div/div/div/div/div/div/div'
		upload_finished = "//div[contains(@class, 'btn-cancel')]"
		upload_confirmation = "//video" 
		process_confirmation = "//*[@id='root']/div/div/div/div[2]/div[2]/div[1]/div[2]/div/img"

		description = "//div[@contenteditable='true']"

		visibility = "//div[@class='tiktok-select-selector']"
		options = ["Public", "Friends", "Private"]

		hashtags = "//div[@class='mentionSuggestions']//*[contains(text(), '{}')]"
		mentions = "//div[contains(concat(' ', normalize-space(@class), ' '), 'user-id') and .='{}']/.."

		mention_box = "//input[contains(concat(' ', normalize-space(@class), ' '), 'search-friends')]"

		comment = "//label[.='Comment']/following-sibling::div/input"
		duet = "//label[.='Duet']/following-sibling::div/input"
		stitch = "//label[.='Stitch']/following-sibling::div/input"

		post = "//div[contains(@class, 'btn-post')]"
		post_confirmation = "//div[contains(@class, 'tiktok-modal__modal-button')]"


		edit_button = "div.edit-card.selected button"

		search_field = "input.search-bar-input"

		music_card = "div.music-card-info"
		add_music = "div.music-card-operation > button"

		# last button
		save_button = "div.modal-header-btn-group > button:last-child"


		go_to_upload_list = "div.tiktok-modal__modal-button.is-line"

	[selectors.schedule]
		switch = "//*[@id='tux-3']"

		date_picker = "//div[contains(@class, 'date-picker-input')]"
		calendar = "//div[contains(@class, 'calendar-wrapper')]"
		calendar_month = "//span[contains(@class, 'month-title')]"
		calendar_valid_days = "//div[@class='jsx-4172176419 days-wrapper']//span[contains(@class, 'day') and contains(@class, 'valid')]"
		calendar_arrows = "//span[contains(@class, 'arrow')]"  # first last, second next

		time_picker = "//div[contains(@class, 'time-picker-input')]"
		time_picker_text = "//div[contains(@class, 'time-picker-input')]/*[1]"
		time_picker_container = "//div[@class='tiktok-timepicker-time-picker-container']"
		timepicker_hours = "//span[contains(@class, 'tiktok-timepicker-left')]"
		timepicker_minutes = "//span[contains(@class, 'tiktok-timepicker-right')]"

	[selectors.upload.cookies_banner]
		banner = "tiktok-cookie-banner"
		button = "div.button-wrapper"

	[selectors.search]
		top_item = "div[data-e2e='search_top-item'] a"
		comment_input = "div[data-e2e='comment-input']"
		comment_text = "div[data-contents='true']"
		username = 'span[data-e2e="browse-username"]'
